baseURL = 'https://joaovicmendes.xyz/'
languageCode = 'en-us'
title = 'joaovicmendes'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[params.homeInfoParams]
title = "João Victor Mendes Freire"
content = "Software Engineer"
